### ISSUE TITLE
TRACE source download and install pointers needed.

### ISSUE THREAD

**Issue by brettviren** [DUNE-DAQ/app-framework-base#23]
A link to TRACE's source download and any install instructions would be welcome here:

https://github.com/DUNE-DAQ/app-framework-base/wiki/Third-Party-Software

**Comment by brettviren** [comment]
I found the git repo link in my email and added that.  @ron003 if that's not correct please correct.  It's README looks enough for instructions.

**Comment by brettviren** [comment]
Reopening.  I don't see how CMake is supposed to find TRACE.  The TRACE UPS product has `TRACEConfig.cmake  TRACEConfigVersion.cmake`.  How are these produced and installed?

**Comment by ron003** [comment]
I was asking Eric that question yesterday, I think. The answer seems to be that they are produced by the cetmodules build environment.
I'm in the process of adding them to the trace repo, but I currently am not exactly sure how to do it.

On Fri, 2020-05-22 at 11:41 -0700, Brett Viren wrote:

Reopening. I don't see how CMake is supposed to find TRACE. The TRACE UPS product has TRACEConfig.cmake TRACEConfigVersion.cmake. How are these produced and installed?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DUNE-2DDAQ_app-2Dframework-2Dbase_issues_23-23issuecomment-2D632847771&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=7KXkqf0bzyUQv15jBKEcHw&m=80wqZmv3PULV1CrCjk9rrqe9ug5v7ke29NpgU9W3_3A&s=IP4c4-63YRuEd4RpOBjUsf-gT_mMbkoDv56tkZj8kl8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGH7VZTZYPDVBLXAGEFB4JTRS3BNLANCNFSM4NIBRDIQ&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=7KXkqf0bzyUQv15jBKEcHw&m=80wqZmv3PULV1CrCjk9rrqe9ug5v7ke29NpgU9W3_3A&s=sRbEP60sRjDpcnlzSjjOVmRSp8o83-ZKG9V95G4ro6c&e=>.

--

Ron Rechenmacher
Engineer, Tools and Advanced Computing
Fermi National Accelerator Laboratory
Batavia, IL  60510
